name: Build and Test RESTful Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package

      - name: Build the container image
        run: docker build . -t drake-restful-service

      - name: Run the container
        run: docker run -d -p 8080:8080 drake-restful-service

      - name: Test the RESTful service
        run: |
          # Wait for the container to start up
          sleep 15
          
          # Send a GET request to the service
          response=$(curl http://localhost:8080/api/fib?length=3)
          
          # Check that the response is "Hello world."
          if [ "$response" == "0, 1, 1" ]; then
            echo "Test passed!"
          else
            echo "Test failed. Expected '0, 1, 1', got '$response'"
            exit 1
          fi
